env:
  AWS_REGION: us-west-2
  
name: 'Helm'


on:
  workflow_dispatch

jobs:
  helm:
    name: 'helm'
    runs-on: ubuntu-latest
    environment: production

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3
      

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1.7.0
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
   
    - name: connect cluster
      run: aws eks --region us-west-2 update-kubeconfig --name ex-eks-fargate

    - name: install nginx
      run: helm upgrade --install nginx helm/nginx